version: "3.7"
services:

  postgres:
    image: postgres:12-alpine
    container_name: postgres-12a
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      #POSTGRES_DB: ${PG_DATABASE}
      POSTGRES_USER: ${PG_USERNAME}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - ./bancoFiles/postgres:/data/postgres
    env_file:
      - ./config/env

  app:
    image: teste/teste_pratico-app:0.1.0
    container_name: teste_pratico-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    build:
      dockerfile: Dockerfile